name: Licensee Check

on: [push, pull_request]

jobs:
  licensee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install licensee
        run: sudo apt-get update && sudo apt-get install -y ruby-full && sudo gem install licensee
      - name: Run licensee
        run: licensee detect . --json 