name: SPDX Header Check

on: [push, pull_request]

jobs:
  spdx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run SPDX header check
        run: bash traceform/scripts/check_spdx.sh 